# Generated by Django 3.1.3 on 2020-11-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='overall_rating',
        ),
    ]
