# Generated by Django 3.1.3 on 2020-11-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_remove_restaurant_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='overall_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
