# Generated by Django 3.1.3 on 2020-11-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_restaurant_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
